### ISSUE TITLE
ViewTransition - Missing Documentation

### ISSUE THREAD

**Issue by GrandSchtroumpf** [mdn/mdn#643]
There is some missing documentation for the ViewTransition API

### Types
https://developer.chrome.com/docs/web-platform/view-transitions/same-document#view-transition-types

`startViewTransition` now supports an object as argument and 
```ts
const transition = document.startViewTransition({
  update: updateTheDOMSomehow,
  types: ['slide', direction],
});
console.log(transition.types); // ViewTransitionTypeSet 
```

### view-transition-class
https://developer.chrome.com/docs/web-platform/view-transitions/same-document#view-transition-class
`view-transition-class` targets multiple elements with different `view-transition-name`

### Types
https://developer.chrome.com/docs/web-platform/view-transitions/same-document#view-transition-types
It's possible to select element when a specific type of view transition happens: 
```css
html:active-view-transition-type(slide, backwards) {
  :root {
    view-transition-name: none;
  }
}
```
